/**
 * Comprehensive letter definitions with educational metadata
 */

export interface LetterMetadata {
    letter: string;
    upperCase: string;
    lowerCase: string;
    phoneme: string; // Primary sound
    alternatePhonemes?: string[]; // Alternative sounds
    exampleWords: string[];
    frequency: number; // Letter frequency in English (%)
    difficulty: 'easy' | 'medium' | 'hard';
    confusionPairs: string[]; // Letters commonly confused with this one
    strokeCount: number;
    hasClosedShape: boolean;
    hasCurves: boolean;
    hasDiagonals: boolean;
    category: 'straight' | 'curved' | 'mixed';
    typicalMasteryAge: number; // Age in years
    commonErrors: string[];
    teachingTips: string[];
    visualDescription: string;
}

export const LETTER_DEFINITIONS: Record<string, LetterMetadata> = {
    A: {
        letter: 'A',
        upperCase: 'A',
        lowerCase: 'a',
        phoneme: 'æ',
        alternatePhonemes: ['eɪ', 'ɑ'],
        exampleWords: ['apple', 'ant', 'axe'],
        frequency: 8.2,
        difficulty: 'medium',
        confusionPairs: ['V'],
        strokeCount: 3,
        hasClosedShape: true,
        hasCurves: false,
        hasDiagonals: true,
        category: 'straight',
        typicalMasteryAge: 5,
        commonErrors: ['Missing crossbar', 'Uneven sides', 'Too narrow'],
        teachingTips: [
            'Start at the top left',
            'Make a tent shape',
            'Add the crossbar in the middle',
        ],
        visualDescription: 'Two diagonal lines meeting at top, connected by horizontal bar',
    },

    B: {
        letter: 'B',
        upperCase: 'B',
        lowerCase: 'b',
        phoneme: 'b',
        exampleWords: ['ball', 'bat', 'book'],
        frequency: 1.5,
        difficulty: 'medium',
        confusionPairs: ['D', 'P', 'R'],
        strokeCount: 2,
        hasClosedShape: true,
        hasCurves: true,
        hasDiagonals: false,
        category: 'curved',
        typicalMasteryAge: 5,
        commonErrors: ['Reversed to D', 'Uneven bumps', 'Open shapes'],
        teachingTips: [
            'Vertical line first',
            'Two bumps on the right',
            'Bottom bump is bigger',
        ],
        visualDescription: 'Vertical line with two bumps on the right side',
    },

    C: {
        letter: 'C',
        upperCase: 'C',
        lowerCase: 'c',
        phoneme: 'k',
        alternatePhonemes: ['s'],
        exampleWords: ['cat', 'car', 'cup'],
        frequency: 2.8,
        difficulty: 'easy',
        confusionPairs: ['O', 'G'],
        strokeCount: 1,
        hasClosedShape: false,
        hasCurves: true,
        hasDiagonals: false,
        category: 'curved',
        typicalMasteryAge: 4,
        commonErrors: ['Too closed (like O)', 'Too open', 'Backwards'],
        teachingTips: [
            'Start at the top',
            'Curve around like a moon',
            'Leave a gap on the right',
        ],
        visualDescription: 'Large curve open on the right side',
    },

    D: {
        letter: 'D',
        upperCase: 'D',
        lowerCase: 'd',
        phoneme: 'd',
        exampleWords: ['dog', 'dad', 'door'],
        frequency: 4.3,
        difficulty: 'easy',
        confusionPairs: ['B', 'O'],
        strokeCount: 2,
        hasClosedShape: true,
        hasCurves: true,
        hasDiagonals: false,
        category: 'curved',
        typicalMasteryAge: 5,
        commonErrors: ['Reversed to B', 'Too round', 'Flat curve'],
        teachingTips: [
            'Vertical line first',
            'Big curve on the right',
            'Curve connects top and bottom',
        ],
        visualDescription: 'Vertical line with large curve on the right',
    },

    E: {
        letter: 'E',
        upperCase: 'E',
        lowerCase: 'e',
        phoneme: 'ɛ',
        alternatePhonemes: ['i', 'ə'],
        exampleWords: ['egg', 'elephant', 'eye'],
        frequency: 12.7,
        difficulty: 'easy',
        confusionPairs: ['F'],
        strokeCount: 4,
        hasClosedShape: false,
        hasCurves: false,
        hasDiagonals: false,
        category: 'straight',
        typicalMasteryAge: 4,
        commonErrors: ['Unequal lines', 'Missing middle bar', 'Slanted'],
        teachingTips: [
            'Vertical line first',
            'Three horizontal lines',
            'Top and bottom are longest',
        ],
        visualDescription: 'Vertical line with three horizontal lines extending right',
    },

    F: {
        letter: 'F',
        upperCase: 'F',
        lowerCase: 'f',
        phoneme: 'f',
        exampleWords: ['fish', 'fan', 'fox'],
        frequency: 2.2,
        difficulty: 'easy',
        confusionPairs: ['E', 'T'],
        strokeCount: 3,
        hasClosedShape: false,
        hasCurves: false,
        hasDiagonals: false,
        category: 'straight',
        typicalMasteryAge: 4,
        commonErrors: ['Too similar to E', 'Missing crossbar', 'Wrong proportions'],
        teachingTips: [
            'Vertical line first',
            'Top horizontal line',
            'Middle crossbar',
        ],
        visualDescription: 'Vertical line with two horizontal lines at top and middle',
    },

    G: {
        letter: 'G',
        upperCase: 'G',
        lowerCase: 'g',
        phoneme: 'g',
        alternatePhonemes: ['dʒ'],
        exampleWords: ['goat', 'girl', 'game'],
        frequency: 2.0,
        difficulty: 'medium',
        confusionPairs: ['C', 'O'],
        strokeCount: 2,
        hasClosedShape: false,
        hasCurves: true,
        hasDiagonals: false,
        category: 'curved',
        typicalMasteryAge: 6,
        commonErrors: ['Looks like C', 'Missing horizontal bar', 'Too round'],
        teachingTips: [
            'Start like C',
            'Add a horizontal bar inside',
            'Bar points left',
        ],
        visualDescription: 'C shape with horizontal bar extending inward from right',
    },

    H: {
        letter: 'H',
        upperCase: 'H',
        lowerCase: 'h',
        phoneme: 'h',
        exampleWords: ['hat', 'house', 'hand'],
        frequency: 6.1,
        difficulty: 'easy',
        confusionPairs: ['N'],
        strokeCount: 3,
        hasClosedShape: false,
        hasCurves: false,
        hasDiagonals: false,
        category: 'straight',
        typicalMasteryAge: 4,
        commonErrors: ['Crossbar too high/low', 'Uneven verticals', 'Like N'],
        teachingTips: [
            'Two vertical lines',
            'Connect with horizontal bar in middle',
            'Keep bars parallel',
        ],
        visualDescription: 'Two vertical lines connected by horizontal bar in middle',
    },

    I: {
        letter: 'I',
        upperCase: 'I',
        lowerCase: 'i',
        phoneme: 'ɪ',
        alternatePhonemes: ['aɪ'],
        exampleWords: ['ice', 'igloo', 'inch'],
        frequency: 7.0,
        difficulty: 'easy',
        confusionPairs: ['L', 'T'],
        strokeCount: 3,
        hasClosedShape: false,
        hasCurves: false,
        hasDiagonals: false,
        category: 'straight',
        typicalMasteryAge: 4,
        commonErrors: ['Missing top/bottom bars', 'Tilted', 'Too wide'],
        teachingTips: [
            'Vertical line in center',
            'Small horizontal lines at top and bottom',
            'Keep it narrow',
        ],
        visualDescription: 'Vertical line with short horizontal caps at top and bottom',
    },

    J: {
        letter: 'J',
        upperCase: 'J',
        lowerCase: 'j',
        phoneme: 'dʒ',
        exampleWords: ['jump', 'jar', 'juice'],
        frequency: 0.15,
        difficulty: 'medium',
        confusionPairs: ['I'],
        strokeCount: 1,
        hasClosedShape: false,
        hasCurves: true,
        hasDiagonals: false,
        category: 'curved',
        typicalMasteryAge: 5,
        commonErrors: ['Hook too big/small', 'Not curved enough', 'Like I'],
        teachingTips: [
            'Straight line down',
            'Hook to the left at bottom',
            'Keep hook small',
        ],
        visualDescription: 'Vertical line curving left at bottom',
    },

    K: {
        letter: 'K',
        upperCase: 'K',
        lowerCase: 'k',
        phoneme: 'k',
        exampleWords: ['kite', 'king', 'key'],
        frequency: 0.77,
        difficulty: 'medium',
        confusionPairs: ['X'],
        strokeCount: 3,
        hasClosedShape: false,
        hasCurves: false,
        hasDiagonals: true,
        category: 'straight',
        typicalMasteryAge: 6,
        commonErrors: ['Diagonals dont meet', 'Wrong angles', 'Like X'],
        teachingTips: [
            'Vertical line first',
            'Diagonal from top meets middle',
            'Diagonal from middle goes to bottom right',
        ],
        visualDescription: 'Vertical line with two diagonals meeting at middle',
    },

    L: {
        letter: 'L',
        upperCase: 'L',
        lowerCase: 'l',
        phoneme: 'l',
        exampleWords: ['lion', 'leg', 'lamp'],
        frequency: 4.0,
        difficulty: 'easy',
        confusionPairs: ['I', 'T'],
        strokeCount: 2,
        hasClosedShape: false,
        hasCurves: false,
        hasDiagonals: false,
        category: 'straight',
        typicalMasteryAge: 4,
        commonErrors: ['Not perpendicular', 'Base too long/short', 'Like I or T'],
        teachingTips: [
            'Vertical line down',
            'Horizontal line to the right',
            'Make an L shape',
        ],
        visualDescription: 'Vertical line with horizontal line extending right at bottom',
    },

    M: {
        letter: 'M',
        upperCase: 'M',
        lowerCase: 'm',
        phoneme: 'm',
        exampleWords: ['mom', 'moon', 'mouse'],
        frequency: 2.4,
        difficulty: 'hard',
        confusionPairs: ['W', 'N'],
        strokeCount: 4,
        hasClosedShape: false,
        hasCurves: false,
        hasDiagonals: true,
        category: 'mixed',
        typicalMasteryAge: 6,
        commonErrors: ['Reversed to W', 'Uneven humps', 'Too narrow'],
        teachingTips: [
            'Two vertical lines at edges',
            'V shape in the middle',
            'Three points at bottom',
        ],
        visualDescription: 'Two vertical lines connected by inverted V in middle',
    },

    N: {
        letter: 'N',
        upperCase: 'N',
        lowerCase: 'n',
        phoneme: 'n',
        exampleWords: ['nose', 'net', 'nest'],
        frequency: 6.7,
        difficulty: 'medium',
        confusionPairs: ['M', 'H', 'U'],
        strokeCount: 3,
        hasClosedShape: false,
        hasCurves: false,
        hasDiagonals: true,
        category: 'straight',
        typicalMasteryAge: 5,
        commonErrors: ['Reversed to U', 'Diagonal wrong direction', 'Like H'],
        teachingTips: [
            'Two vertical lines',
            'Diagonal connects top-left to bottom-right',
            'Keep parallel',
        ],
        visualDescription: 'Two vertical lines connected by diagonal from top-left to bottom-right',
    },

    O: {
        letter: 'O',
        upperCase: 'O',
        lowerCase: 'o',
        phoneme: 'ɒ',
        alternatePhonemes: ['oʊ', 'ʌ'],
        exampleWords: ['octopus', 'orange', 'owl'],
        frequency: 7.5,
        difficulty: 'easy',
        confusionPairs: ['Q', 'C', 'D'],
        strokeCount: 1,
        hasClosedShape: true,
        hasCurves: true,
        hasDiagonals: false,
        category: 'curved',
        typicalMasteryAge: 4,
        commonErrors: ['Not round enough', 'Oval instead of circle', 'Gap in circle'],
        teachingTips: [
            'Make a circle',
            'Start at top',
            'Close it completely',
        ],
        visualDescription: 'Complete circular shape',
    },

    P: {
        letter: 'P',
        upperCase: 'P',
        lowerCase: 'p',
        phoneme: 'p',
        exampleWords: ['pig', 'pen', 'pizza'],
        frequency: 1.9,
        difficulty: 'easy',
        confusionPairs: ['B', 'R', 'Q'],
        strokeCount: 2,
        hasClosedShape: true,
        hasCurves: true,
        hasDiagonals: false,
        category: 'curved',
        typicalMasteryAge: 5,
        commonErrors: ['Reversed to Q', 'Bump too big', 'Like B'],
        teachingTips: [
            'Vertical line first',
            'One bump at top on the right',
            'Bump is smaller than B',
        ],
        visualDescription: 'Vertical line with curved bump at top right',
    },

    Q: {
        letter: 'Q',
        upperCase: 'Q',
        lowerCase: 'q',
        phoneme: 'kw',
        exampleWords: ['queen', 'quick', 'quiet'],
        frequency: 0.095,
        difficulty: 'medium',
        confusionPairs: ['O', 'P'],
        strokeCount: 2,
        hasClosedShape: true,
        hasCurves: true,
        hasDiagonals: true,
        category: 'curved',
        typicalMasteryAge: 6,
        commonErrors: ['Like O', 'Tail too long/short', 'Tail wrong direction'],
        teachingTips: [
            'Make an O first',
            'Add a small tail at bottom-right',
            'Tail points diagonal',
        ],
        visualDescription: 'Circle with small diagonal tail at bottom-right',
    },

    R: {
        letter: 'R',
        upperCase: 'R',
        lowerCase: 'r',
        phoneme: 'r',
        exampleWords: ['rabbit', 'red', 'run'],
        frequency: 6.0,
        difficulty: 'medium',
        confusionPairs: ['P', 'B'],
        strokeCount: 3,
        hasClosedShape: true,
        hasCurves: true,
        hasDiagonals: true,
        category: 'mixed',
        typicalMasteryAge: 6,
        commonErrors: ['Like P', 'Leg wrong angle', 'Bump too big'],
        teachingTips: [
            'Vertical line first',
            'Bump at top like P',
            'Diagonal leg from middle to bottom-right',
        ],
        visualDescription: 'Vertical line with curved bump at top and diagonal leg from middle',
    },

    S: {
        letter: 'S',
        upperCase: 'S',
        lowerCase: 's',
        phoneme: 's',
        alternatePhonemes: ['z'],
        exampleWords: ['sun', 'snake', 'star'],
        frequency: 6.3,
        difficulty: 'medium',
        confusionPairs: ['Z', '5'],
        strokeCount: 1,
        hasClosedShape: false,
        hasCurves: true,
        hasDiagonals: false,
        category: 'curved',
        typicalMasteryAge: 5,
        commonErrors: ['Backwards', 'Too straight', 'Not smooth'],
        teachingTips: [
            'Start at top-right',
            'Curve left, then right',
            'Like a snake',
        ],
        visualDescription: 'S-shaped double curve',
    },

    T: {
        letter: 'T',
        upperCase: 'T',
        lowerCase: 't',
        phoneme: 't',
        exampleWords: ['tree', 'top', 'ten'],
        frequency: 9.1,
        difficulty: 'easy',
        confusionPairs: ['I', 'L', 'F'],
        strokeCount: 2,
        hasClosedShape: false,
        hasCurves: false,
        hasDiagonals: false,
        category: 'straight',
        typicalMasteryAge: 4,
        commonErrors: ['Crossbar not centered', 'Too wide', 'Like I'],
        teachingTips: [
            'Horizontal line at top',
            'Vertical line down from center',
            'Make a T shape',
        ],
        visualDescription: 'Vertical line with horizontal line at top',
    },

    U: {
        letter: 'U',
        upperCase: 'U',
        lowerCase: 'u',
        phoneme: 'ʌ',
        alternatePhonemes: ['u', 'ju'],
        exampleWords: ['umbrella', 'up', 'under'],
        frequency: 2.8,
        difficulty: 'easy',
        confusionPairs: ['V', 'N'],
        strokeCount: 1,
        hasClosedShape: false,
        hasCurves: true,
        hasDiagonals: false,
        category: 'curved',
        typicalMasteryAge: 5,
        commonErrors: ['Like V', 'Not curved enough', 'Reversed to N'],
        teachingTips: [
            'Start at top-left',
            'Curve down and up',
            'Ends at top-right',
        ],
        visualDescription: 'U-shaped curve connecting two vertical lines',
    },

    V: {
        letter: 'V',
        upperCase: 'V',
        lowerCase: 'v',
        phoneme: 'v',
        exampleWords: ['van', 'vase', 'violin'],
        frequency: 0.98,
        difficulty: 'easy',
        confusionPairs: ['U', 'A'],
        strokeCount: 2,
        hasClosedShape: false,
        hasCurves: false,
        hasDiagonals: true,
        category: 'straight',
        typicalMasteryAge: 5,
        commonErrors: ['Like U', 'Too wide', 'Uneven sides'],
        teachingTips: [
            'Two diagonal lines',
            'Meet at bottom point',
            'Make a V shape',
        ],
        visualDescription: 'Two diagonal lines meeting at bottom point',
    },

    W: {
        letter: 'W',
        upperCase: 'W',
        lowerCase: 'w',
        phoneme: 'w',
        exampleWords: ['water', 'window', 'wind'],
        frequency: 2.4,
        difficulty: 'hard',
        confusionPairs: ['M'],
        strokeCount: 4,
        hasClosedShape: false,
        hasCurves: false,
        hasDiagonals: true,
        category: 'straight',
        typicalMasteryAge: 6,
        commonErrors: ['Reversed to M', 'Uneven points', 'Too narrow'],
        teachingTips: [
            'Like two Vs side by side',
            'Four diagonal lines',
            'Three points at bottom',
        ],
        visualDescription: 'Four diagonal lines forming two connected V shapes',
    },

    X: {
        letter: 'X',
        upperCase: 'X',
        lowerCase: 'x',
        phoneme: 'ks',
        alternatePhonemes: ['gz', 'z'],
        exampleWords: ['x-ray', 'box', 'fox'],
        frequency: 0.15,
        difficulty: 'easy',
        confusionPairs: ['K'],
        strokeCount: 2,
        hasClosedShape: false,
        hasCurves: false,
        hasDiagonals: true,
        category: 'straight',
        typicalMasteryAge: 5,
        commonErrors: ['Not centered', 'Like K', 'Wrong angles'],
        teachingTips: [
            'Two diagonal lines',
            'Cross in the middle',
            'Make an X',
        ],
        visualDescription: 'Two diagonal lines crossing in center',
    },

    Y: {
        letter: 'Y',
        upperCase: 'Y',
        lowerCase: 'y',
        phoneme: 'j',
        alternatePhonemes: ['ɪ', 'aɪ'],
        exampleWords: ['yellow', 'yes', 'yoyo'],
        frequency: 2.0,
        difficulty: 'easy',
        confusionPairs: ['V'],
        strokeCount: 3,
        hasClosedShape: false,
        hasCurves: false,
        hasDiagonals: true,
        category: 'straight',
        typicalMasteryAge: 5,
        commonErrors: ['Like V', 'Stem too short/long', 'Uneven top'],
        teachingTips: [
            'Two diagonal lines meet in middle',
            'Vertical line down from middle',
            'Top looks like V',
        ],
        visualDescription: 'Two diagonals meeting in middle with vertical line downward',
    },

    Z: {
        letter: 'Z',
        upperCase: 'Z',
        lowerCase: 'z',
        phoneme: 'z',
        exampleWords: ['zebra', 'zoo', 'zero'],
        frequency: 0.074,
        difficulty: 'easy',
        confusionPairs: ['S', 'N'],
        strokeCount: 3,
        hasClosedShape: false,
        hasCurves: false,
        hasDiagonals: true,
        category: 'straight',
        typicalMasteryAge: 5,
        commonErrors: ['Reversed', 'Like S', 'Lines not parallel'],
        teachingTips: [
            'Horizontal line at top',
            'Diagonal line down',
            'Horizontal line at bottom',
        ],
        visualDescription: 'Horizontal lines at top and bottom connected by diagonal',
    },
};

/**
 * Letter categorization utilities
 */
export const LetterCategories = {
    // By difficulty
    easy: ['C', 'E', 'F', 'H', 'I', 'L', 'O', 'T', 'U', 'V', 'X', 'Y', 'Z'],
    medium: ['A', 'B', 'D', 'G', 'J', 'K', 'N', 'P', 'Q', 'R', 'S'],
    hard: ['M', 'W'],

    // By shape type
    straight: ['E', 'F', 'H', 'I', 'K', 'L', 'T', 'V', 'W', 'X', 'Y', 'Z'],
    curved: ['B', 'C', 'D', 'G', 'J', 'O', 'P', 'Q', 'S', 'U'],
    mixed: ['A', 'M', 'N', 'R'],

    // By common confusions
    mirrorPairs: [
        ['B', 'D'],
        ['P', 'Q'],
    ],
    rotationPairs: [
        ['N', 'U'],
        ['M', 'W'],
    ],
    similarShapes: [
        ['C', 'G', 'O'],
        ['E', 'F'],
        ['I', 'L', 'T'],
        ['V', 'U'],
    ],
};

export default LETTER_DEFINITIONS;
